package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"errors"
	"fmt"
	"time"

	"example.com/Course-Service/v2/graph/model"
	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
)

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.CourseInput) (*model.Course, error) {
	// Generate UUID before insertion
	newUUID := uuid.New().String()

	query := `
        INSERT INTO courses (
            id,
            name, 
            price, 
            duration, 
            description, 
            status, 
            difficulty, 
            instructor
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
        RETURNING id, created_at, updated_at
    `

	var id string
	var createdAt, updatedAt time.Time

	err := r.DB.QueryRow(
		ctx,
		query,
		newUUID, // Use generated UUID
		input.Name,
		input.Price,
		input.Duration,
		input.Description,
		input.Status.String(),
		input.Difficulty.String(),
		input.Instructor,
	).Scan(&id, &createdAt, &updatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to create course: %v", err)
	}

	return &model.Course{
		ID:          id,
		Name:        input.Name,
		Price:       input.Price,
		Duration:    input.Duration,
		Description: input.Description,
		Status:      input.Status,
		Difficulty:  input.Difficulty,
		Instructor:  input.Instructor,
		CreatedAt:   createdAt,
		UpdatedAt:   updatedAt,
	}, nil
}

// UpdateCourse is the resolver for the updateCourse field.
func (r *mutationResolver) UpdateCourse(ctx context.Context, id string, input model.CourseInput) (*model.Course, error) {
	query := `
        UPDATE courses
        SET 
            name = $1,
            price = $2,
            duration = $3,
            description = $4,
            status = $6,
            difficulty = $7,
            instructor = $8,
            updated_at = NOW()
        WHERE id = $9
        RETURNING enrollees, created_at, updated_at
    `

	var (
		enrollees int32
		createdAt time.Time
		updatedAt time.Time
	)

	err := r.DB.QueryRow(
		ctx,
		query,
		input.Name,
		input.Price,
		input.Duration,
		input.Description,
		input.Status.String(),
		input.Difficulty.String(),
		input.Instructor,
		id, // WHERE clause parameter
	).Scan(&enrollees, &createdAt, &updatedAt)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("course with id %s not found", id)
		}
		return nil, fmt.Errorf("failed to update course: %w", err)
	}

	return &model.Course{
		ID:          id,
		Name:        input.Name,
		Price:       input.Price,
		Duration:    input.Duration,
		Description: input.Description,
		Status:      input.Status,
		Difficulty:  input.Difficulty,
		Instructor:  input.Instructor,
		Enrollees:   enrollees,
		CreatedAt:   createdAt,
		UpdatedAt:   updatedAt,
	}, nil
}

// DeleteCourse is the resolver for the deleteCourse field.
func (r *mutationResolver) DeleteCourseByName(ctx context.Context, name string) (bool, error) {
	_, err := r.DB.Exec(ctx, `
		DELETE FROM courses
		WHERE name = $1
	`, name)

	if err != nil {
		return false, nil
	} else {
		return true, nil
	}
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
	rows, err := r.DB.Query(ctx, `
        SELECT 
            id, name, price, duration, description, enrollees, 
            status, difficulty, instructor, created_at, updated_at
        FROM courses
    `)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch courses: %w", err)
	}
	defer rows.Close()

	var courses []*model.Course
	for rows.Next() {
		var course model.Course
		err := rows.Scan(
			&course.ID,
			&course.Name,
			&course.Price,
			&course.Duration,
			&course.Description,
			&course.Enrollees,
			&course.Status,
			&course.Difficulty,
			&course.Instructor,
			&course.CreatedAt,
			&course.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan course: %w", err)
		}
		courses = append(courses, &course)
	}

	return courses, nil
}

// Course is the resolver for the course field.
func (r *queryResolver) Course(ctx context.Context, courseID string) (*model.Course, error) {
	var course model.Course
	err := r.DB.QueryRow(ctx, `
        SELECT 
            id, name, price, duration, description, enrollees, 
            status, difficulty, instructor, created_at, updated_at
        FROM courses
        WHERE id = $1
    `, courseID).Scan(
		&course.ID,
		&course.Name,
		&course.Price,
		&course.Duration,
		&course.Description,
		&course.Enrollees,
		&course.Status,
		&course.Difficulty,
		&course.Instructor,
		&course.CreatedAt,
		&course.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("course with id %s not found", courseID)
		}
		return nil, fmt.Errorf("failed to fetch course: %w", err)
	}

	return &course, nil
}

// CoursesByDifficulty is the resolver for the coursesByDifficulty field.
// CoursesByDifficulty is the resolver for the coursesByDifficulty field.
func (r *queryResolver) CoursesByDifficulty(ctx context.Context, difficulty model.DifficultyLevel) ([]*model.Course, error) {
	rows, err := r.DB.Query(ctx, `
        SELECT 
            id, name, price, duration, description, enrollees, 
            status, difficulty, instructor, created_at, updated_at
        FROM courses
        WHERE difficulty = $1
    `, difficulty.String())
	if err != nil {
		return nil, fmt.Errorf("failed to fetch courses by difficulty: %w", err)
	}
	defer rows.Close()

	var courses []*model.Course
	for rows.Next() {
		var course model.Course
		err := rows.Scan(
			&course.ID,
			&course.Name,
			&course.Price,
			&course.Duration,
			&course.Description,
			&course.Enrollees,
			&course.Status,
			&course.Difficulty,
			&course.Instructor,
			&course.CreatedAt,
			&course.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan course: %w", err)
		}
		courses = append(courses, &course)
	}

	return courses, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
