package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"errors"
	"fmt"
	"time"
	"sync"
	"example.com/Course-Service/v2/graph/model"
	pgx "github.com/jackc/pgx/v5"
)

var (
    courseCreatedChannel       = make(chan *model.Course)
    courseUpdatedChannel       = make(chan *model.Course)
    courseDeletedByNameChannel = make(chan bool)
    mu                         sync.Mutex // Mutex for concurrency safety
)

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.CourseInput) (*model.Course, error) {
	query := `
        INSERT INTO courses (
            id,
            name, 
            price, 
            duration, 
            description, 
            status, 
            difficulty, 
            instructor
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
        RETURNING id, created_at, updated_at
    `

	var id string
	var createdAt, updatedAt time.Time

	err := r.DB.QueryRow(
		ctx,
		query,
		input.ID,
		input.Name,
		input.Price,
		input.Duration,
		input.Description,
		input.Status.String(),
		input.Difficulty.String(),
		input.Instructor,
	).Scan(&id, &createdAt, &updatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to create course: %v", err)
	}

	course := &model.Course{
		ID:          id,
		Name:        input.Name,
		Price:       input.Price,
		Duration:    input.Duration,
		Description: input.Description,
		Status:      input.Status,
		Difficulty:  input.Difficulty,
		Instructor:  input.Instructor,
		CreatedAt:   createdAt,
		UpdatedAt:   updatedAt,
	}

	// 🔴 Publish to subscription channel
	go func() {
		courseCreatedChannel <- &model.Course{
			ID:          id,
			Name:        input.Name,
			Price:       input.Price,
			Duration:    input.Duration,
			Description: input.Description,
			Status:      input.Status,
			Difficulty:  input.Difficulty,
			Instructor:  input.Instructor,
			CreatedAt:   createdAt,
			UpdatedAt:   updatedAt,
		}
	}()

	return course, nil
}

// UpdateCourse is the resolver for the updateCourse field.
func (r *mutationResolver) UpdateCourse(ctx context.Context, id string, input model.CourseInput) (*model.Course, error) {
	query := `
        UPDATE courses
        SET 
            name = $1,
            price = $2,
            duration = $3,
            description = $4,
            status = $6,
            difficulty = $7,
            instructor = $8,
            updated_at = NOW()
        WHERE id = $9
        RETURNING created_at, updated_at
    `

	var (
		createdAt time.Time
		updatedAt time.Time
	)

	err := r.DB.QueryRow(
		ctx,
		query,
		input.Name,
		input.Price,
		input.Duration,
		input.Description,
		input.Status.String(),
		input.Difficulty.String(),
		input.Instructor,
		id,
	).Scan(&createdAt, &updatedAt)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("course with id %s not found", id)
		}
		return nil, fmt.Errorf("failed to update course: %w", err)
	}

	course := &model.Course{
		ID:          id,
		Name:        input.Name,
		Price:       input.Price,
		Duration:    input.Duration,
		Description: input.Description,
		Status:      input.Status,
		Difficulty:  input.Difficulty,
		Instructor:  input.Instructor,
		CreatedAt:   createdAt,
		UpdatedAt:   updatedAt,
	}

	// 🔴 Publish to subscription channel
	go func() {
		courseUpdatedChannel <- course
	}()

	return course, nil
}


// DeleteCourse is the resolver for the deleteCourse field.
func (r *mutationResolver) DeleteCourseByName(ctx context.Context, name string) (bool, error) {
	cmdTag, err := r.DB.Exec(ctx, `
		DELETE FROM courses
		WHERE name = $1
	`, name)

	if err != nil {
		return false, err
	}

	deleted := cmdTag.RowsAffected() > 0
	if deleted {
		// 🔴 Publish to subscription channel
		go func() {
			courseDeletedByNameChannel <- true
		}()
	}

	return deleted, nil
}


// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
	rows, err := r.DB.Query(ctx, `
        SELECT 
            id, name, price, duration, description, 
            status, difficulty, instructor, created_at, updated_at
        FROM courses
    `)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch courses: %w", err)
	}
	defer rows.Close()

	var courses []*model.Course
	for rows.Next() {
		var course model.Course
		err := rows.Scan(
			&course.ID,
			&course.Name,
			&course.Price,
			&course.Duration,
			&course.Description,
			&course.Status,
			&course.Difficulty,
			&course.Instructor,
			&course.CreatedAt,
			&course.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan course: %w", err)
		}
		courses = append(courses, &course)
	}

	return courses, nil
}

// Course is the resolver for the course field.
func (r *queryResolver) Course(ctx context.Context, courseID string) (*model.Course, error) {
	var course model.Course
	err := r.DB.QueryRow(ctx, `
        SELECT 
            id, name, price, duration, description, 
            status, difficulty, instructor, created_at, updated_at
        FROM courses
        WHERE id = $1
    `, courseID).Scan(
		&course.ID,
		&course.Name,
		&course.Price,
		&course.Duration,
		&course.Description,
		&course.Status,
		&course.Difficulty,
		&course.Instructor,
		&course.CreatedAt,
		&course.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("course with id %s not found", courseID)
		}
		return nil, fmt.Errorf("failed to fetch course: %w", err)
	}

	return &course, nil
}

// CourseCreated is the resolver for the courseCreated field.
// CourseCreated is the resolver for the courseCreated subscription.
func (r *subscriptionResolver) CourseCreated(ctx context.Context) (<-chan *model.Course, error) {
	events := make(chan *model.Course)

	go func() {
		for course := range courseCreatedChannel {
			select {
			case <-ctx.Done():
				close(events)
				return
			case events <- course:
			}
		}
	}()

	return events, nil
}

// CourseUpdated is the resolver for the courseUpdated subscription.
func (r *subscriptionResolver) CourseUpdated(ctx context.Context) (<-chan *model.Course, error) {
	events := make(chan *model.Course)

	go func() {
		for course := range courseUpdatedChannel {
			select {
			case <-ctx.Done():
				close(events)
				return
			case events <- course:
			}
		}
	}()

	return events, nil
}

// CourseDeletedByName is the resolver for the courseDeletedByName subscription.
func (r *subscriptionResolver) CourseDeletedByName(ctx context.Context) (<-chan bool, error) {
	events := make(chan bool)

	go func() {
		for deleted := range courseDeletedByNameChannel {
			select {
			case <-ctx.Done():
				close(events)
				return
			case events <- deleted:
			}
		}
	}()

	return events, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
