package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"
	"time"

	"example.com/Course-Service/v2/graph/model"
)

// Mutation Resolvers
func (r *mutationResolver) CreateCourse(ctx context.Context, name string, price float64) (*model.Course, error) {
	storage.mutex.Lock()
	defer storage.mutex.Unlock()

	course := &model.Course{
		ID:    generateID(),
		Name:  name,
		Price: price,
	}
	// Assign to the map instead of using append
	storage.courses[course.ID] = course
	return course, nil
}

// EnrollUser is the resolver for the enrollUser field.
func (r *mutationResolver) EnrollUser(ctx context.Context, userID int32, courseID string) (*model.Enrollment, error) {
	storage.mutex.Lock()
	defer storage.mutex.Unlock()

	course, err := r.Resolver.Course(ctx, courseID)
	if err != nil {
		return nil, fmt.Errorf("course not found: %w", err)
	}

	enrollment := &model.Enrollment{
		ID:         generateID(),
		UserID:     userID,
		Course:     course,
		EnrolledAt: time.Now().Format(time.RFC3339),
	}
	storage.enrollments = append(storage.enrollments, enrollment)
	return enrollment, nil
}

// CreateSubject is the resolver for the createSubject field.
func (r *mutationResolver) CreateSubject(ctx context.Context, name string, description *string) (*model.Subject, error) {
	storage.mutex.Lock()
	defer storage.mutex.Unlock()

	subject := &model.Subject{
		ID:          generateID(),
		Name:        name,
		Description: description,
	}
	storage.subjects = append(storage.subjects, subject)
	return subject, nil
}

// CreateTeacher is the resolver for the createTeacher field.
func (r *mutationResolver) CreateTeacher(ctx context.Context, name string, email string, specialization *string) (*model.Teacher, error) {
	storage.mutex.Lock()
	defer storage.mutex.Unlock()

	teacher := &model.Teacher{
		ID:             generateID(),
		Name:           name,
		Email:          email,
		Specialization: specialization,
	}
	storage.teachers = append(storage.teachers, teacher)
	return teacher, nil
}

// CreateSchedule is the resolver for the createSchedule field.
func (r *mutationResolver) CreateSchedule(ctx context.Context, courseID string, startTime string, endTime string) (*model.Schedule, error) {
	storage.mutex.Lock()
	defer storage.mutex.Unlock()

	course, err := r.Resolver.Course(ctx, courseID)
	if err != nil {
		return nil, fmt.Errorf("course not found: %w", err)
	}

	schedule := &model.Schedule{
		ID:        generateID(),
		Course:    course,
		StartTime: startTime,
		EndTime:   endTime,
	}
	storage.schedules = append(storage.schedules, schedule)
	return schedule, nil
}

// Query Resolvers
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
	storage.mutex.RLock()
	defer storage.mutex.RUnlock()

	// Convert map values to a slice
	courses := make([]*model.Course, 0, len(storage.courses))
	for _, course := range storage.courses {
		courses = append(courses, course)
	}
	return courses, nil
}

// Course is the resolver for the course field.
func (r *queryResolver) Course(ctx context.Context, id string) (*model.Course, error) {
	return r.Resolver.Course(ctx, id)
}

// Enrollments is the resolver for the enrollments field.
func (r *queryResolver) Enrollments(ctx context.Context) ([]*model.Enrollment, error) {
	return storage.enrollments, nil
}

// Subjects is the resolver for the subjects field.
func (r *queryResolver) Subjects(ctx context.Context) ([]*model.Subject, error) {
	return storage.subjects, nil
}

// Teachers is the resolver for the teachers field.
func (r *queryResolver) Teachers(ctx context.Context) ([]*model.Teacher, error) {
	return storage.teachers, nil
}

// Schedules is the resolver for the schedules field.
func (r *queryResolver) Schedules(ctx context.Context) ([]*model.Schedule, error) {
	return storage.schedules, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
