// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type SignupInput struct {
	Username    string   `json:"username"`
	Email       string   `json:"email"`
	Password    string   `json:"password"`
	PhoneNumber *string  `json:"phoneNumber,omitempty"`
	Birthdate   *string  `json:"birthdate,omitempty"`
	Gender      *string  `json:"gender,omitempty"`
	Location    *string  `json:"location,omitempty"`
	Bio         *string  `json:"bio,omitempty"`
	Interests   []string `json:"interests,omitempty"`
}

type Student struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	Email       string  `json:"email"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Birthdate   *string `json:"birthdate,omitempty"`
	Gender      *string `json:"gender,omitempty"`
	Location    *string `json:"location,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}
