// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginEvent struct {
	Username string `json:"username"`
	Message  string `json:"message"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Mutation struct {
}

type Profile struct {
	FullName    string  `json:"fullName"`
	Age         int32   `json:"age"`
	Bio         *string `json:"bio,omitempty"`
	Location    *string `json:"location,omitempty"`
	Interests   *string `json:"interests,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Gender      *string `json:"gender,omitempty"`
	Email       string  `json:"email"`
	Birthdate   *string `json:"birthdate,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Subscription struct {
}

type UpdateProfileInput struct {
	Username    string  `json:"username"`
	FullName    *string `json:"fullName,omitempty"`
	Birthdate   *string `json:"birthdate,omitempty"`
	Bio         *string `json:"bio,omitempty"`
	Location    *string `json:"location,omitempty"`
	Interests   *string `json:"interests,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Gender      *string `json:"gender,omitempty"`
	Email       *string `json:"email,omitempty"`
}
