type Mutation {
  # Register a new user
  register(input: RegisterInput!): RegisterResponse!

  # Login a user
  login(input: LoginInput!): LoginResponse!

  # Update the profile of a student
  updateProfile(input: UpdateProfileInput!): Profile!
}

type Subscription {
  # Subscription for user login events
  profileUpdated(username: String!): Profile
  userLoggedIn: LoginEvent!
}

type Query {
  # Fetch the profile of a student by username
  getProfile(username: String!): Profile!
}

type Profile {
  fullName: String!
  age: Int! # Add age as a calculated field
  bio: String
  location: String
  interests: String
  phoneNumber: String
  gender: String
  email: String!
  birthdate: String # Add birthdate field
}

input RegisterInput {
  fullName: String!
  email: String!
  username: String!
  password: String!
}

input LoginInput {
  username: String!
  password: String!
}

input UpdateProfileInput {
  currentUsername: String! # The current username to identify the user
  newUsername: String       # The new username (optional)
  fullName: String
  birthdate: String
  bio: String
  location: String
  interests: String
  phoneNumber: String
  gender: String
  email: String
}

type RegisterResponse {
  success: Boolean!
  message: String!
}

type LoginResponse {
  success: Boolean!
  message: String!
}

type LoginEvent {
  username: String!
  message: String!
}