package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"log"
	"student-service/graph/model"
	"sync"
)

// Mutation: Register a new user
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.RegisterResponse, error) {
	// Check if the username or email already exists in the students table
	var exists bool
	err := r.DB.QueryRowContext(ctx, "SELECT EXISTS(SELECT 1 FROM students WHERE username = $1 OR email = $2)", input.Username, input.Email).Scan(&exists)
	if err != nil {
		log.Printf("Error checking student existence: %v", err)
		return &model.RegisterResponse{Success: false, Message: "Internal server error while checking student existence"}, nil
	}
	if exists {
		return &model.RegisterResponse{Success: false, Message: "Username or email already exists"}, nil
	}

	// Hash the password
	hashedPassword := hashPassword(input.Password)

	// Insert the student into the students table
	_, err = r.DB.ExecContext(ctx, "INSERT INTO students (fullName, email, username, password) VALUES ($1, $2, $3, $4)", input.FullName, input.Email, input.Username, hashedPassword)
	if err != nil {
		log.Printf("Error inserting student: %v", err)
		return &model.RegisterResponse{Success: false, Message: "Failed to create account"}, nil
	}

	return &model.RegisterResponse{Success: true, Message: "Account created successfully"}, nil
}

// Mutation: Login a user
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginResponse, error) {
	// Fetch the user by username
	var hashedPassword string
	err := r.DB.QueryRowContext(ctx, "SELECT password FROM students WHERE username = $1", input.Username).Scan(&hashedPassword)
	if err != nil {
		log.Printf("Invalid username: %s", input.Username)
		return &model.LoginResponse{Success: false, Message: "Incorrect username or password"}, nil
	}

	// Verify the password
	if hashedPassword != hashPassword(input.Password) {
		log.Printf("Invalid password for username: %s", input.Username)
		return &model.LoginResponse{Success: false, Message: "Incorrect username or password"}, nil
	}

	// Notify subscribers about the login event
	go func() {
		loginSubscribers.Lock()
		defer loginSubscribers.Unlock()
		for _, subscriber := range loginSubscribers.subscribers {
			subscriber <- &model.LoginEvent{
				Username: input.Username,
				Message:  "User logged in successfully",
			}
		}
	}()

	return &model.LoginResponse{Success: true, Message: "Login successful!!"}, nil
}

// HealthCheck is the resolver for the healthCheck field.
func (r *queryResolver) HealthCheck(ctx context.Context) (string, error) {
	return "Server is healthy", nil
}

// Subscription: User logged in
func (r *subscriptionResolver) UserLoggedIn(ctx context.Context) (<-chan *model.LoginEvent, error) {
	loginSubscribers.Lock()
	defer loginSubscribers.Unlock()

	ch := make(chan *model.LoginEvent, 1)
	loginSubscribers.subscribers = append(loginSubscribers.subscribers, ch)

	go func() {
		<-ctx.Done()
		loginSubscribers.Lock()
		defer loginSubscribers.Unlock()
		for i, subscriber := range loginSubscribers.subscribers {
			if subscriber == ch {
				loginSubscribers.subscribers = append(loginSubscribers.subscribers[:i], loginSubscribers.subscribers[i+1:]...)
				break
			}
		}
		close(ch)
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var loginSubscribers = struct {
	sync.Mutex
	subscribers []chan *model.LoginEvent
}{}

func hashPassword(password string) string {
	hash := sha256.Sum256([]byte(password))
	return hex.EncodeToString(hash[:])
}
