type Query {
  healthCheck: String!
}

type Student {
  id: ID!
  username: String!
  email: String!
  phoneNumber: String
  birthdate: String
  gender: String
  location: String
  createdAt: String!
  updatedAt: String!
}

input SignupInput {
  username: String!
  email: String!
  password: String!
  phoneNumber: String
  birthdate: String
  gender: String
  location: String
  bio: String
  interests: [String!]
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  signup(input: SignupInput!): Student!
  login(input: LoginInput!): String!
}
