package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"log"
	"sync"
	"time"

	"student-service/graph/model"

	"github.com/lib/pq"
)

// Helper function to hash passwords
func hashPassword(password string) string {
	hash := sha256.Sum256([]byte(password))
	return hex.EncodeToString(hash[:])
}

// Global variable to manage login subscribers
var loginSubscribers = struct {
	sync.Mutex
	subscribers []chan *model.LoginEvent
}{}

// Mutation: Register a new user
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.RegisterResponse, error) {
	// Check if the username or email already exists
	var exists bool
	err := r.DB.QueryRowContext(ctx, "SELECT EXISTS(SELECT 1 FROM students WHERE username = $1 OR email = $2)", input.Username, input.Email).Scan(&exists)
	if err != nil {
		log.Printf("Error checking student existence: %v", err)
		return &model.RegisterResponse{Success: false, Message: "Internal server error"}, nil
	}
	if exists {
		return &model.RegisterResponse{Success: false, Message: "Username or email already exists"}, nil
	}

	// Hash the password
	hashedPassword := hashPassword(input.Password)

	// Insert the user into the database
	_, err = r.DB.ExecContext(ctx, "INSERT INTO students (fullname, email, username, password) VALUES ($1, $2, $3, $4)", input.FullName, input.Email, input.Username, hashedPassword)
	if err != nil {
		log.Printf("Error inserting student: %v", err)
		return &model.RegisterResponse{Success: false, Message: "Failed to create account"}, nil
	}

	return &model.RegisterResponse{Success: true, Message: "Account created successfully"}, nil
}

// Mutation: Login a user
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginResponse, error) {
	// Fetch the user by username
	var hashedPassword string
	err := r.DB.QueryRowContext(ctx, "SELECT password FROM students WHERE username = $1", input.Username).Scan(&hashedPassword)
	if err != nil {
		log.Printf("Invalid username: %s", input.Username)
		return &model.LoginResponse{Success: false, Message: "Incorrect username or password"}, nil
	}

	// Verify the password
	if hashedPassword != hashPassword(input.Password) {
		log.Printf("Invalid password for username: %s", input.Username)
		return &model.LoginResponse{Success: false, Message: "Incorrect username or password"}, nil
	}

	// Notify subscribers of the login event
	loginSubscribers.Lock()
	for _, subscriber := range loginSubscribers.subscribers {
		subscriber <- &model.LoginEvent{
			Username: input.Username,
			Message:  "User logged in",
		}
	}
	loginSubscribers.Unlock()

	return &model.LoginResponse{Success: true, Message: "Login successful!"}, nil
}

// Mutation: Update the profile of a student
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.Profile, error) {
	query := `
        UPDATE students
        SET fullname = COALESCE($1, fullname),
            bio = COALESCE($2, bio),
            location = COALESCE($3, location),
            interests = COALESCE($4, interests),
            phone_number = COALESCE($5, phone_number),
            gender = COALESCE($6, gender),
            email = COALESCE($7, email)
        WHERE username = $8
        RETURNING fullname, bio, location, interests, phone_number, gender, email
    `

	var profile model.Profile
	err := r.DB.QueryRowContext(ctx, query,
		input.FullName,
		input.Bio,
		input.Location,
		pq.Array(input.Interests), // Use pq.Array to handle arrays
		input.PhoneNumber,
		input.Gender,
		input.Email,
		input.Username,
	).Scan(
		&profile.FullName,
		&profile.Bio,
		&profile.Location,
		pq.Array(&profile.Interests), // Ensure interests are returned as an array
		&profile.PhoneNumber,
		&profile.Gender,
		&profile.Email,
	)
	if err != nil {
		log.Printf("Error updating profile: %v", err)
		return nil, err
	}

	return &profile, nil
}

// Query: Fetch the profile of a student by username
func (r *queryResolver) GetProfile(ctx context.Context, username string) (*model.Profile, error) {
	var profile model.Profile
	var birthdate sql.NullString

	query := `
        SELECT fullname, email, birthdate, bio, location, interests, phone_number, gender
        FROM students
        WHERE username = $1
    `
	err := r.DB.QueryRowContext(ctx, query, username).Scan(
		&profile.FullName,
		&profile.Email,
		&birthdate,
		&profile.Bio,
		&profile.Location,
		&profile.Interests,
		&profile.PhoneNumber,
		&profile.Gender,
	)
	if err != nil {
		log.Printf("Error fetching profile: %v", err)
		return nil, err
	}

	// Calculate age if birthdate is available
	if birthdate.Valid {
		birthdateTime, _ := time.Parse("2006-01-02", birthdate.String)
		age := int32(time.Now().Sub(birthdateTime).Hours() / 24 / 365)
		profile.Age = &age
	}

	return &profile, nil
}

// Subscription: User logged in
func (r *subscriptionResolver) UserLoggedIn(ctx context.Context) (<-chan *model.LoginEvent, error) {
	ch := make(chan *model.LoginEvent, 1)

	loginSubscribers.Lock()
	loginSubscribers.subscribers = append(loginSubscribers.subscribers, ch)
	loginSubscribers.Unlock()

	go func() {
		<-ctx.Done()
		loginSubscribers.Lock()
		for i, subscriber := range loginSubscribers.subscribers {
			if subscriber == ch {
				loginSubscribers.subscribers = append(loginSubscribers.subscribers[:i], loginSubscribers.subscribers[i+1:]...)
				break
			}
		}
		loginSubscribers.Unlock()
		close(ch)
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
