type Query {
  healthCheck: String!
}

type Mutation {
  register(input: RegisterInput!): RegisterResponse!
  login(input: LoginInput!): LoginResponse!
}

type Subscription {
  userLoggedIn: LoginEvent!
}

input RegisterInput {
  fullName: String!
  email: String!
  username: String!
  password: String!
}

input LoginInput {
  username: String!
  password: String!
}

type RegisterResponse {
  success: Boolean!
  message: String!
}

type LoginResponse {
  success: Boolean!
  message: String!
}

type LoginEvent {
  username: String!
  message: String!
}