// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Course struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Price       float64         `json:"price"`
	Duration    string          `json:"duration"`
	Description string          `json:"description"`
	Enrollees   int32           `json:"enrollees"`
	Status      CourseStatus    `json:"status"`
	Difficulty  DifficultyLevel `json:"difficulty"`
	Instructor  string          `json:"instructor"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
	Enrollments []*Enrollment   `json:"enrollments"`
}

type CourseInput struct {
	Name        string          `json:"name"`
	Price       float64         `json:"price"`
	Duration    string          `json:"duration"`
	Description string          `json:"description"`
	Status      CourseStatus    `json:"status"`
	Difficulty  DifficultyLevel `json:"difficulty"`
	Instructor  string          `json:"instructor"`
}

type Enrollment struct {
	ID         string           `json:"id"`
	Course     *Course          `json:"course"`
	Student    *Student         `json:"student"`
	Status     EnrollmentStatus `json:"status"`
	EnrolledAt time.Time        `json:"enrolledAt"`
	CreatedAt  time.Time        `json:"createdAt"`
	UpdatedAt  time.Time        `json:"updatedAt"`
}

type EnrollmentInput struct {
	CourseID  string           `json:"courseId"`
	StudentID string           `json:"studentId"`
	Status    EnrollmentStatus `json:"status"`
}

type Mutation struct {
}

type Query struct {
}

type Student struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CourseStatus string

const (
	CourseStatusAvailable   CourseStatus = "AVAILABLE"
	CourseStatusUnavailable CourseStatus = "UNAVAILABLE"
	CourseStatusEnlisted    CourseStatus = "ENLISTED"
)

var AllCourseStatus = []CourseStatus{
	CourseStatusAvailable,
	CourseStatusUnavailable,
	CourseStatusEnlisted,
}

func (e CourseStatus) IsValid() bool {
	switch e {
	case CourseStatusAvailable, CourseStatusUnavailable, CourseStatusEnlisted:
		return true
	}
	return false
}

func (e CourseStatus) String() string {
	return string(e)
}

func (e *CourseStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CourseStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CourseStatus", str)
	}
	return nil
}

func (e CourseStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DifficultyLevel string

const (
	DifficultyLevelIntroduction DifficultyLevel = "INTRODUCTION"
	DifficultyLevelBeginner     DifficultyLevel = "BEGINNER"
	DifficultyLevelIntermediate DifficultyLevel = "INTERMEDIATE"
	DifficultyLevelAdvanced     DifficultyLevel = "ADVANCED"
)

var AllDifficultyLevel = []DifficultyLevel{
	DifficultyLevelIntroduction,
	DifficultyLevelBeginner,
	DifficultyLevelIntermediate,
	DifficultyLevelAdvanced,
}

func (e DifficultyLevel) IsValid() bool {
	switch e {
	case DifficultyLevelIntroduction, DifficultyLevelBeginner, DifficultyLevelIntermediate, DifficultyLevelAdvanced:
		return true
	}
	return false
}

func (e DifficultyLevel) String() string {
	return string(e)
}

func (e *DifficultyLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DifficultyLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DifficultyLevel", str)
	}
	return nil
}

func (e DifficultyLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EnrollmentStatus string

const (
	EnrollmentStatusActive    EnrollmentStatus = "ACTIVE"
	EnrollmentStatusCompleted EnrollmentStatus = "COMPLETED"
	EnrollmentStatusCancelled EnrollmentStatus = "CANCELLED"
)

var AllEnrollmentStatus = []EnrollmentStatus{
	EnrollmentStatusActive,
	EnrollmentStatusCompleted,
	EnrollmentStatusCancelled,
}

func (e EnrollmentStatus) IsValid() bool {
	switch e {
	case EnrollmentStatusActive, EnrollmentStatusCompleted, EnrollmentStatusCancelled:
		return true
	}
	return false
}

func (e EnrollmentStatus) String() string {
	return string(e)
}

func (e *EnrollmentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EnrollmentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EnrollmentStatus", str)
	}
	return nil
}

func (e EnrollmentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
