// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Course struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Price     float64     `json:"price"`
	Schedules []*Schedule `json:"schedules,omitempty"`
	Subjects  []*Subject  `json:"subjects,omitempty"`
	Teachers  []*Teacher  `json:"teachers,omitempty"`
}

type Enrollment struct {
	ID         string  `json:"id"`
	UserID     int32   `json:"userId"`
	Course     *Course `json:"course"`
	EnrolledAt string  `json:"enrolledAt"`
}

type Mutation struct {
}

type Query struct {
}

type Schedule struct {
	ID        string         `json:"id"`
	Course    *Course        `json:"course"`
	StartTime string         `json:"startTime"`
	EndTime   string         `json:"endTime"`
	Days      []*ScheduleDay `json:"days,omitempty"`
}

type ScheduleDay struct {
	Schedule *Schedule `json:"schedule"`
	Day      DayEnum   `json:"day"`
}

type Subject struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Teacher struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	Specialization *string   `json:"specialization,omitempty"`
	Courses        []*Course `json:"courses,omitempty"`
}

type DayEnum string

const (
	DayEnumMonday    DayEnum = "MONDAY"
	DayEnumTuesday   DayEnum = "TUESDAY"
	DayEnumWednesday DayEnum = "WEDNESDAY"
	DayEnumThursday  DayEnum = "THURSDAY"
	DayEnumFriday    DayEnum = "FRIDAY"
	DayEnumSaturday  DayEnum = "SATURDAY"
	DayEnumSunday    DayEnum = "SUNDAY"
)

var AllDayEnum = []DayEnum{
	DayEnumMonday,
	DayEnumTuesday,
	DayEnumWednesday,
	DayEnumThursday,
	DayEnumFriday,
	DayEnumSaturday,
	DayEnumSunday,
}

func (e DayEnum) IsValid() bool {
	switch e {
	case DayEnumMonday, DayEnumTuesday, DayEnumWednesday, DayEnumThursday, DayEnumFriday, DayEnumSaturday, DayEnumSunday:
		return true
	}
	return false
}

func (e DayEnum) String() string {
	return string(e)
}

func (e *DayEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DayEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DayEnum", str)
	}
	return nil
}

func (e DayEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
