// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Registration struct {
	ID         string  `json:"id"`
	StudentID  string  `json:"studentID"`
	CourseID   string  `json:"courseID"`
	Term       string  `json:"term"`
	Grade      *string `json:"grade,omitempty"`
	Status     string  `json:"status"`
	EnrolledAt string  `json:"enrolledAt"`
	UpdatedAt  string  `json:"updatedAt"`
}

type RegistrationInput struct {
	StudentID string  `json:"studentID"`
	CourseID  string  `json:"courseID"`
	Term      string  `json:"term"`
	Grade     *string `json:"grade,omitempty"`
	Status    string  `json:"status"`
}
